-- =================================================================
-- NNE SafetyHUB - Spot Checks Module Database Table SQL
-- =================================================================

CREATE TABLE IF NOT EXISTS `spot_checks` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `spot_check_ref` VARCHAR(100) NOT NULL UNIQUE,
  `work_package` VARCHAR(255) NULL,
  `date` DATE NULL,
  `time` VARCHAR(50) NULL,
  `building_id` INT NULL,
  `building_name` VARCHAR(255) NULL,
  `floor_level` VARCHAR(150) NULL,
  `location` TEXT NULL,
  `selected_rooms` JSON NULL,
  `selected_zones` JSON NULL,
  `weather` VARCHAR(255) NULL,
  `activity_name` VARCHAR(255) NULL,
  `company_involved` VARCHAR(255) NULL,
  `permit_id` VARCHAR(100) NULL,
  `rams_id` VARCHAR(100) NULL,
  `high_risk_activities` JSON NULL,
  `if_hot_work` VARCHAR(100) NULL,
  `chk1_2` VARCHAR(20) NULL,
  `chk1_3` VARCHAR(20) NULL,
  `chk1_4` VARCHAR(20) NULL,
  `chk1_5` VARCHAR(20) NULL,
  `chk1_6` VARCHAR(20) NULL,
  `chk1_7` VARCHAR(20) NULL,
  `chk1_8` VARCHAR(20) NULL,
  `chk2_1` VARCHAR(20) NULL,
  `briefing_date` DATE NULL,
  `briefing_time` VARCHAR(50) NULL,
  `conducted_by` VARCHAR(255) NULL,
  `participants` VARCHAR(50) NULL,
  `key_topics` JSON NULL,
  `other_topic` TEXT NULL,
  `chk2_1_5` VARCHAR(20) NULL,
  `explain_no_briefing` TEXT NULL,
  `chk3_2` VARCHAR(20) NULL,
  `safety_issue_created` VARCHAR(20) NULL,
  `safety_issue_ref` VARCHAR(100) NULL,
  `findings` TEXT NULL,
  `corrective_actions` JSON NULL,
  `foreman_name` VARCHAR(255) NULL,
  `foreman_company` VARCHAR(255) NULL,
  `foreman_date` DATE NULL,
  `foreman_signature` LONGTEXT NULL,
  `attachments` JSON NULL,
  `inspector_name` VARCHAR(255) NULL,
  `inspector_company` VARCHAR(255) NULL,
  `inspector_date` DATE NULL,
  `inspector_signature` LONGTEXT NULL,
  `status` ENUM('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'CLOSED') NOT NULL DEFAULT 'COMPLETED',
  `created_by_user_id` INT NULL,
  `created_by_user_name` VARCHAR(255) NULL,
  `created_by_role` VARCHAR(100) NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
